# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_indicator', models.IntegerField()),
                ('nmi', models.CharField(max_length=10)),
                ('register_id', models.CharField(max_length=10)),
                ('meter_serial_number', models.CharField(max_length=10)),
                ('meter_reading_value', models.CharField(max_length=20)),
                ('reading_date_time', models.DateTimeField(verbose_name='Reading Date Time')),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
