# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
